trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'freakyfashion-api'
  tag: '$(Build.BuildId)'

steps:

- checkout: self

# BUILD (utan registry!)
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: $(imageName)
    dockerfile: Dockerfile
    tags: |
      $(tag)

# PUSH (kopplar registry via service connection)
- task: Docker@2
  displayName: Push image to ACR
  inputs:
    command: push
    repository: $(imageName)
    containerRegistry: 'mcratzacr'
    tags: |
      $(tag)